=== andreiulinici/fleet-management-xml/Public/fleet_management.dtd
<!DOCTYPE fleet_management [

<!ELEMENT fleet_management (drivers, vehicles)>
<!ELEMENT drivers (driver*)>
<!ELEMENT driver (firstName, lastName, id, address, email, phoneNumber, distanceTraveled)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phoneNumber (#PCDATA)>
<!ELEMENT distanceTraveled (#PCDATA)>
<!ELEMENT vehicles (vehicle*)>
<!ELEMENT vehicle (details, trips)>
<!ELEMENT details (manufacturer, model, registrationPlate, vin, engineCapacity, fuelType, horsepower, fuelConsumption, kilometrage)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT registrationPlate (#PCDATA)>
<!ELEMENT vin (#PCDATA)>
<!ELEMENT engineCapacity (#PCDATA)>
<!ELEMENT fuelType (#PCDATA)>
<!ELEMENT horsepower (#PCDATA)>
<!ELEMENT fuelConsumption (#PCDATA)>
<!ELEMENT kilometrage (#PCDATA)>
<!ELEMENT trips (trip*)>
<!ELEMENT trip (tripId, tripDriver, startDate, startLocation, stopDate, stopLocation, distance)>
<!ELEMENT tripId (#PCDATA)>
<!ELEMENT tripDriver (driverFirstName, driverLastName, driverId)>
<!ELEMENT driverFirstName (#PCDATA)>
<!ELEMENT driverLastName (#PCDATA)>
<!ELEMENT driverId (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT startLocation (startLat, startLong)>
<!ELEMENT startLat (#PCDATA)>
<!ELEMENT startLong (#PCDATA)>
<!ELEMENT stopDate (#PCDATA)>
<!ELEMENT stopLocation (stopLat, stopLong)>
<!ELEMENT stopLat (#PCDATA)>
<!ELEMENT stopLong (#PCDATA)>
<!ELEMENT distance (#PCDATA)>

]>

=== andreiulinici/fleet-management-xml/Public/fleet_management.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="fleet_management.xsl"?>
<!DOCTYPE fleet_management SYSTEM "fleet_management.dtd">
<fleet_management>
    <drivers>
        <driver>
            <firstName>John</firstName>
            <lastName>Doe</lastName>
            <id>1810329135411</id>
            <address>Unirii 1, Bucharest</address>
            <email>john.doe@gmail.com</email>
            <phoneNumber>0732166221</phoneNumber>
            <distanceTraveled>200</distanceTraveled>
        </driver>
        <driver>
            <firstName>Anna</firstName>
            <lastName>Craig</lastName>
            <id>2820329135412</id>
            <address>Unirii 2, Bucharest</address>
            <email>anna.craig@gmail.com</email>
            <phoneNumber>0732166222</phoneNumber>
            <distanceTraveled>40</distanceTraveled>
        </driver>
        <driver>
            <firstName>Michael</firstName>
            <lastName>Douglas</lastName>
            <id>1830329135413</id>
            <address>Unirii 3, Bucharest</address>
            <email>michael.douglas@gmail.com</email>
            <phoneNumber>0732166223</phoneNumber>
            <distanceTraveled>130</distanceTraveled>
        </driver>
        <driver>
            <firstName>Richard</firstName>
            <lastName>Gere</lastName>
            <id>1840329135414</id>
            <address>Unirii 4, Bucharest</address>
            <email>richard.gere@gmail.com</email>
            <phoneNumber>0732166224</phoneNumber>
            <distanceTraveled>120</distanceTraveled>
        </driver>
        <driver>
            <firstName>Katy</firstName>
            <lastName>Perry</lastName>
            <id>2850329135415</id>
            <address>Unirii 5, Bucharest</address>
            <email>katy.perry@gmail.com</email>
            <phoneNumber>0732166225</phoneNumber>
            <distanceTraveled>1300</distanceTraveled>
        </driver>
        <driver>
            <firstName>Sam</firstName>
            <lastName>Smith</lastName>
            <id>1860329135416</id>
            <address>Unirii 6, Bucharest</address>
            <email>sam.smith@gmail.com</email>
            <phoneNumber>0732166226</phoneNumber>
            <distanceTraveled>635</distanceTraveled>
        </driver>
        <driver>
            <firstName>Will</firstName>
            <lastName>Smith</lastName>
            <id>1870329135417</id>
            <address>Unirii 7, Bucharest</address>
            <email>will.smith@gmail.com</email>
            <phoneNumber>0732166227</phoneNumber>
            <distanceTraveled>5400</distanceTraveled>
        </driver>
    </drivers>

    <vehicles>
        <vehicle>
            <details>
                <manufacturer>Citroen</manufacturer>
                <model>C3</model>
                <registrationPlate>B-58-PKA</registrationPlate>
                <vin>VF7FCK6EK8A001151</vin>
                <engineCapacity>1200</engineCapacity>
                <fuelType>Petrol</fuelType>
                <horsepower>67</horsepower>
                <fuelConsumption>6.1</fuelConsumption>
                <kilometrage>10000</kilometrage>
            </details>
            <trips>
                <trip>
                    <tripId>B-58-PKA-0000</tripId>
                    <tripDriver>
                        <driverFirstName>John</driverFirstName>
                        <driverLastName>Doe</driverLastName>
                        <driverId>1810329135411</driverId>
                    </tripDriver>
                    <startDate>2017-03-21T13:28:06.419Z</startDate>
                    <startLocation>
                        <startLat>44.4378043</startLat>
                        <startLong>26.0245982</startLong>
                    </startLocation>
                    <stopDate>2017-03-21T16:28:00.000Z</stopDate>
                    <stopLocation>
                        <stopLat>44.3338331</stopLat>
                        <stopLong>28.0247929</stopLong>
                    </stopLocation>
                    <distance>160</distance>
                </trip>
                <trip>
                    <tripId>B-58-PKA-0001</tripId>
                    <tripDriver>
                        <driverFirstName>John</driverFirstName>
                        <driverLastName>Doe</driverLastName>
                        <driverId>1810329135411</driverId>
                    </tripDriver>
                    <startDate>2017-03-22T10:28:06.419Z</startDate>
                    <startLocation>
                        <startLat>44.2462965</startLat>
                        <startLong>28.2683479</startLong>
                    </startLocation>
                    <stopDate>2017-03-22T13:28:06.419Z</stopDate>
                    <stopLocation>
                        <stopLat>44.1812565</stopLat>
                        <stopLong>28.5592996</stopLong>
                    </stopLocation>
                    <distance>40</distance>
                </trip>
            </trips>
        </vehicle>
        <vehicle>
            <details>
                <manufacturer>Ford</manufacturer>
                <model>Transit</model>
                <registrationPlate>B-58-PKB</registrationPlate>
                <vin>VF7FCK6EK8A00112</vin>
                <engineCapacity>1700</engineCapacity>
                <fuelType>Diesel</fuelType>
                <horsepower>163</horsepower>
                <fuelConsumption>6.8</fuelConsumption>
                <kilometrage>20000</kilometrage>
            </details>
            <trips>
                <trip>
                    <tripId>B-58-PKB-0000</tripId>
                    <tripDriver>
                        <driverFirstName>Anna</driverFirstName>
                        <driverLastName>Craig</driverLastName>
                        <driverId>2820329135412</driverId>
                    </tripDriver>
                    <startDate>2017-03-20T09:28:06.419Z</startDate>
                    <startLocation>
                        <startLat>44.2462965</startLat>
                        <startLong>28.2683479</startLong>
                    </startLocation>
                    <stopDate>2017-03-20T12:28:06.419Z</stopDate>
                    <stopLocation>
                        <stopLat>44.1812565</stopLat>
                        <stopLong>28.5592996</stopLong>
                    </stopLocation>
                    <distance>40</distance>
                </trip>
            </trips>
        </vehicle>
        <vehicle>
            <details>
                <manufacturer>Mitsubishi</manufacturer>
                <model>Pajero</model>
                <registrationPlate>B-58-PKC</registrationPlate>
                <vin>VF7FCK6EK8A001153</vin>
                <engineCapacity>3200</engineCapacity>
                <fuelType>Diesel</fuelType>
                <horsepower>200</horsepower>
                <fuelConsumption>8.5</fuelConsumption>
                <kilometrage>30000</kilometrage>
            </details>
            <trips>
                <trip>
                    <tripId>B-58-PKC-0000</tripId>
                    <tripDriver>
                        <driverFirstName>Michael</driverFirstName>
                        <driverLastName>Douglas</driverLastName>
                        <driverId>1830329135413</driverId>
                    </tripDriver>
                    <startDate>2017-03-10T13:28:06.419Z</startDate>
                    <startLocation>
                        <startLat>45.3410878</startLat>
                        <startLong>25.5164496</startLong>
                    </startLocation>
                    <stopDate>2017-03-10T18:28:06.419Z</stopDate>
                    <stopLocation>
                        <stopLat>44.4378043</stopLat>
                        <stopLong>26.0245982</stopLong>
                    </stopLocation>
                    <distance>130</distance>
                </trip>
            </trips>
        </vehicle>
        <vehicle>
            <details>
                <manufacturer>Tesla</manufacturer>
                <model>Model S</model>
                <registrationPlate>B-58-PKD</registrationPlate>
                <vin>VF7FCK6EK8A001154</vin>
                <engineCapacity>0</engineCapacity>
                <fuelType>Electric</fuelType>
                <horsepower>421</horsepower>
                <fuelConsumption>2.64</fuelConsumption>
                <kilometrage>40000</kilometrage>
            </details>
            <trips>
                <trip>
                    <tripId>B-58-PKD-0000</tripId>
                    <tripDriver>
                        <driverFirstName>Richard</driverFirstName>
                        <driverLastName>Gere</driverLastName>
                        <driverId>1840329135414</driverId>
                    </tripDriver>
                    <startDate>2017-04-10T10:28:06.419Z</startDate>
                    <startLocation>
                        <startLat>44.4378043</startLat>
                        <startLong>26.0245982</startLong>
                    </startLocation>
                    <stopDate>2017-04-10T13:28:06.419Z</stopDate>
                    <stopLocation>
                        <stopLat>44.8559646</stopLat>
                        <stopLong>24.8384835</stopLong>
                    </stopLocation>
                    <distance>120</distance>
                </trip>
            </trips>
        </vehicle>
    </vehicles>
</fleet_management>
